"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'django_filters',

    'apps.my_view_set_app.apps.MyViewSetAppConfig',
    'apps.myapp.apps.MyappConfig',
    'apps.book.apps.BookConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# DATABASES

# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
use_mysql = os.getenv('MYSQL') == 'True'

if use_mysql:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'my_django_db'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



#        «Это для меня»

import sys
import codecs

# ვქმნით ლოგების შესანახ ფოლდერს პროექტის ძირეულ დირექტორიაში
LOGS_DIR = BASE_DIR / 'logs'
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,  # ლოგირების კონფიგურაციის სტანდარტული ვერსია (Django-ს მოثხოვნა)
    'disable_existing_loggers': False,  # ინარჩუნებს სხვა არსებულ ლოგერებს (არ თიშავს მათ ავტომატურად)

    # FORMATTERS: აყალიბებს ტექსტის სტრუქტურას (როგორ გამოიყურებოდეს ჩაწერილი ლოგი)
    'formatters': {
        'verbose': {  # დეტალური ფორმატი (აჩვენებს თარიღს, დონეს, სახელს და შეტყობინებას)
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {  # მარტივი ფორმატი (მხოლოდ დონე და ტექსტი)
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    # HANDLERS: განსაზღვრავს სად და რა პირობებით უნდა გაიგზავნოს ლოგები
    'handlers': {
        # 1. სერვერის ლოგების კონსოლში გამომტანი ჰენდლერი (გასწორებული UTF-8 ენქოდინგით)
        'console': {
            'level': 'INFO',  # იჭერს INFO და უფრო მაღალი დონის შეტყობინებებს
            'class': 'logging.StreamHandler',  # უშვებს ლოგებს ტერმინალში/კონსოლში
            'stream': codecs.getwriter('utf-8')(sys.stdout.buffer),  # აძალებს კონსოლს გამოიყენოს UTF-8
            'formatter': 'simple',  # იყენებს მარტივ ფორმატს
        },
        # 2. HTTP მოთხოვნების ფაილში ჩასაწერი ჰენდლერი (RotatingFileHandler-ით)
        'http_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # იცავს ფაილს უსასრულო ზრდისგან
            'filename': LOGS_DIR / 'http_logs.log',  # ფაილის გზა და სახელი
            'formatter': 'verbose',  # იყენებს დეტალურ ფორმატს
            'maxBytes': 1024 * 1024 * 1,  # მაქსიმალური ზომა: 5 მეგაბაიტი
            'backupCount': 3,  # ინახავს მაქსიმუმ 3 ძველ სარეზერვო ფაილს
            'encoding': 'utf-8',
        },
        # 3. ბაზის (SQL) მოთხოვნების ფაილში ჩასაწერი ჰენდლერი (RotatingFileHandler-ით)
        'db_file': {
            'level': 'DEBUG',  # იჭერს ყველაზე დეტალურ (SQL) ლოგებს
            'class': 'logging.handlers.RotatingFileHandler',  # იცავს ფაილს უსასრულო ზრდისგან
            'filename': LOGS_DIR / 'db_logs.log',  # ფაილის გზა და სახელი
            'formatter': 'verbose',  # იყენებს დეტალურ ფორმატს
            'maxBytes': 1024 * 1024 * 1,  # მაქსიმალური ზომა: 1 მეგაბაიტი
            'backupCount': 3,  # ინახავს მაქსიმუმ 3 ძველ სარეზერვო ფაილს
            'encoding': 'utf-8',
        },
    },

    # LOGGERS: აკავშირებს Django-ს შიდა მოდულებს ზემოთ შექმნილ ჰენდლერებთან
    'loggers': {
        # სერვერის მუშაობის პროცესი
        'django.server': {
            'handlers': ['console'],  # აგზავნის მხოლოდ კონსოლში
            'level': 'INFO',
            'propagate': False,
        },
        # HTTP მოთხოვნები და მათი პასუხები/სტატუსები
        'django.request': {
            'handlers': ['http_file', 'console'],  # აგზავნის ფაილშიც (`http_logs.log`) და კონსოლშიც
            'level': 'INFO',
            'propagate': False,
        },
        # დამატებითი არხი უსაფრთხოებისა და სხვა HTTP შემომავალი ტრაფიკისთვის
        'django.security': {
            'handlers': ['http_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # ბაზის მონაცემთა (SQL) მოთხოვნები
        'django.db.backends': {
            'handlers': ['db_file', 'console'],  # დავამატე კონსოლიც, რომ SQL ლოგებიც უპრობლემოდ იბეჭდოს
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}




REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],


# 1. CursorPagination (ამჟამად აქტიური):
    # იყენებს დაშიფრულ კურსორს და არის წარმოუდგენლად სწრაფი დიდი მონაცემთა ბაზებისთვის.
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',

# 2. PageNumberPagination:
    # მუშაობს კლასიკური გვერდების ნომრებით (მაგალითად: ?page=2).
# 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

# 3. LimitOffsetPagination:
    # მუშაობს ლიმიტით და საწყისი წერტილით (მაგალითად: ?limit=5&offset=5).
# 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
#     'PAGE_SIZE': 6,
}





# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'

